<a href="https://colab.research.google.com/github/Hemant8120/SimpleRNN/blob/main/SimpleRNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Listing Installed Packages

In [1]:
!pip list

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
aiohttp                          3.8.6
aiosignal                        1.3.1
alabaster                        0.7.13
albumentations                   1.3.1
altair                           4.2.2
anyio                            3.7.1
appdirs                          1.4.4
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array-record                     0.5.0
arviz                            0.15.1
astropy                          5.3.4
astunparse                       1.6.3
async-timeout                    4.0.3
atpublic                         4.0
attrs                            23.1.0
audioread                        3.0.1
autograd                         1.6.2
Babel                            2.13.1
backcall                         0.2.0
beautifulsoup4                   4.11.2
bidict                           0.22.1
b

###### Here, we are listing the installed Python packages along with their versions.

#1. Importing Necessary Libraries

In [2]:
from keras import Sequential

###### Here, we are importing the Sequential class from the Keras library. Sequential is a linear stack of layers that can be used to build a neural network model layer by layer in a step-by-step fashion.
--------------------------------------------------------------------------------


In [3]:
from keras.layers import Dense, SimpleRNN

###### Here, we are importing the required modules from the Keras library for building a sequential model with a Dense layer and a SimpleRNN layer.
--------------------------------------------------------------------------------

#2. Building the Model

In [4]:
model = Sequential()

######  Here, We are creating an instance of the Sequential model. This instance will be used to build the neural network model by adding layers to it in a sequential manner.
--------------------------------------------------------------------------------

In [5]:
# Adding a SimpleRNN layer to the model with 4 units and input shape (4, 5)
model.add(SimpleRNN(4, input_shape=(4, 5)))

###### Here, we are adding a SimpleRNN layer to the model. This layer has 4 units (neurons) and expects input sequences with a shape of (4, 5), where 4 is the length of each sequence, and 5 is the number of features in each time step.
--------------------------------------------------------------------------------

In [6]:
# Adding a Dense layer with 1 unit and sigmoid activation function to the model
model.add(Dense(1,  activation = "sigmoid"))

###### Here, a sequential model is created with a SimpleRNN layer having 3 units and an input shape of (4,5). This is followed by a Dense layer with 1 unit and a sigmoid activation function.
--------------------------------------------------------------------------------

#3. Model Summary and Weights Inspection

In [7]:
# Displaying a summary of the model's architecture
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 4)                 40        
                                                                 
 dense (Dense)               (None, 1)                 5         
                                                                 
Total params: 45 (180.00 Byte)
Trainable params: 45 (180.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


###### This prints a summary of the model architecture, showing the layers, their types, output shapes, and the total number of parameters.
--------------------------------------------------------------------------------

In [8]:
model.get_weights()              # Get all the weights of the model

[array([[-0.80211747, -0.5295899 , -0.4287811 ,  0.53088486],
        [-0.74338007, -0.07872897,  0.23710167,  0.2595111 ],
        [-0.12252015, -0.3028171 ,  0.38511324,  0.3031329 ],
        [-0.43216267, -0.01252592, -0.14569145, -0.06953382],
        [-0.45232075,  0.14806366,  0.7925863 , -0.05446088]],
       dtype=float32),
 array([[-0.31198943, -0.8710638 ,  0.29956916, -0.23274213],
        [ 0.7886929 , -0.40024573, -0.4468674 , -0.13444877],
        [ 0.02810698,  0.27637628,  0.08982555, -0.9564296 ],
        [ 0.5289956 ,  0.06831864,  0.8381522 ,  0.1140049 ]],
       dtype=float32),
 array([0., 0., 0., 0.], dtype=float32),
 array([[0.19890106],
        [0.9962311 ],
        [0.78303874],
        [0.636397  ]], dtype=float32),
 array([0.], dtype=float32)]

###### Here, we are using the get_weights() method to retrieve all the weights of the model. The returned value is a list containing the weight matrices and bias vectors for each layer in the order they were added to the model.
--------------------------------------------------------------------------------

In [9]:
model.get_weights()[0]           # Get the weights of the first layer

array([[-0.80211747, -0.5295899 , -0.4287811 ,  0.53088486],
       [-0.74338007, -0.07872897,  0.23710167,  0.2595111 ],
       [-0.12252015, -0.3028171 ,  0.38511324,  0.3031329 ],
       [-0.43216267, -0.01252592, -0.14569145, -0.06953382],
       [-0.45232075,  0.14806366,  0.7925863 , -0.05446088]],
      dtype=float32)

###### Here, we are accessing the first element of the list returned by get_weights(), which corresponds to the weights of the first layer in the model.
--------------------------------------------------------------------------------

In [10]:
model.get_weights()[0].shape     # Get the shape of the weights of the first layer

(5, 4)

###### This retrieves the shape of the weight matrix of the first layer. The shape provides information about the dimensions of the weight matrix, indicating the number of neurons in the current layer and the previous layer.
--------------------------------------------------------------------------------

In [11]:
model.get_weights()[1]           # Get the biases of the first layer

array([[-0.31198943, -0.8710638 ,  0.29956916, -0.23274213],
       [ 0.7886929 , -0.40024573, -0.4468674 , -0.13444877],
       [ 0.02810698,  0.27637628,  0.08982555, -0.9564296 ],
       [ 0.5289956 ,  0.06831864,  0.8381522 ,  0.1140049 ]],
      dtype=float32)

###### This accesses the second element of the list returned by get_weights(), which corresponds to the biases of the first layer in the model.
--------------------------------------------------------------------------------

In [12]:
model.get_weights()[1].shape     # Get the shape of the biases of the first layer

(4, 4)

###### This retrieves the shape of the bias vector of the first layer. The shape indicates the number of neurons in the current layer.
--------------------------------------------------------------------------------

#### These above commands are useful for inspecting the individual components of the model's weights, such as weight matrices and bias vectors, which can provide insights into how the model is representing and learning from the input data.
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

# 4. Loading IMDB Dataset

In [13]:
from keras.datasets import imdb   # Importing the IMDB movie reviews dataset from Keras

###### Here, we are using the imdb module from the keras.datasets package to import the IMDB movie reviews dataset. The IMDB dataset is a popular dataset for natural language processing (NLP) tasks, particularly sentiment analysis, where the goal is to classify movie reviews as positive or negative based on their text content.
--------------------------------------------------------------------------------


In [14]:
(X_train, y_train), (X_test, y_test) = imdb.load_data()   # Loading the IMDB movie reviews dataset and splitting it into training and testing sets

###### Here, we are using the load_data() function from the imdb module to load the IMDB movie reviews dataset. The dataset is then split into training and testing sets, with X_train and X_test containing the movie reviews and y_train and y_test containing the corresponding sentiment labels (positive or negative). This is a common step in machine learning where you split your data into training and testing sets to train a model on one set and evaluate its performance on another set to assess generalization.
--------------------------------------------------------------------------------


# 5. Inspecting Length of Reviews

In [15]:
len(X_train[0])   # Outputting the length of the first movie review in the training set

218

###### Here, we are checking and outputting the length of the first movie review in the training set (X_train[0]). This can be useful to understand the number of words or tokens in the first review, providing insight into the structure and complexity of the data. It's a common exploratory step to get a sense of the input data before building and training a model.
--------------------------------------------------------------------------------


In [16]:
len(X_train[1])   # Outputting the length of the second movie review in the training set

189

###### Here, we are checking and outputting the length of the second movie review in the training set (X_train[1]). Similar to the previous comment, this helps in understanding the variation in the lengths of different movie reviews in the dataset, which can be important for preprocessing and configuring the neural network model.
--------------------------------------------------------------------------------


In [17]:
len(X_train[2])   # Outputting the length of the third movie review in the training set

141

###### In this case, you are checking and outputting the length of the third movie review in the training set (X_train[2]). This information is valuable for understanding the distribution of review lengths in the dataset and can be crucial for determining the appropriate padding or truncation strategy during data preprocessing.
--------------------------------------------------------------------------------

# 6. Text Data Preprocessing:

In [18]:
mylist=[]                          # Creating an empty list called 'mylist'
for review in X_train:             # Iterating through each movie review in the training set
  mylist.append(len(review))       # Appending the length of each review to 'mylist'

min(mylist)                        # Finding and outputting the minimum length among all the reviews

11

###### In this code snippet, you are creating an empty list (mylist), then iterating through each movie review in the training set (X_train). For each review, you calculate its length and append that length to the mylist. Finally, you determine and output the minimum length among all the reviews using the min function. This can be useful for understanding the range of review lengths in the dataset and deciding on an appropriate padding or truncation strategy.
--------------------------------------------------------------------------------

In [19]:
X_train.shape   # Outputting the shape of the training set X_train

(25000,)

###### This code is displaying the shape of the training set (X_train). The shape typically represents the number of samples and the length of each sample in the dataset. The exact output will depend on the structure of your data, but it will give you insights into the dimensions of your training set. For example, if the output is (n_samples, max_length), it indicates the number of movie reviews in the training set (n_samples) and the maximum length of a review (max_length).
--------------------------------------------------------------------------------

In [20]:
X_test.shape   # Outputting the shape of the test set X_test

(25000,)

###### This code is displaying the shape of the test set (X_test). Similar to the previous comment about X_train.shape, this will provide information about the number of samples and the length of each sample in the test set. Understanding the shape of the test set is crucial for evaluating the performance of a machine learning model on unseen data.
--------------------------------------------------------------------------------

# 7. Text Tokenization and Padding:

In [21]:
import numpy as np   # Importing the NumPy library and assigning it the alias 'np' for convenience

In [22]:
sent = [
      "india won worldcup",
      "rohit played very well",
      "above all is my imagination",
      "bharat mata ki jay",
      "definatly we goona win next worldcup"
]   # Creating a list 'sent' containing five string elements, each representing a sentence or statement

###### The import numpy as np statement is importing the NumPy library and giving it the alias 'np'. NumPy is a powerful library in Python for numerical and mathematical operations.
--------------------------------------------------------------------------------

#### The sent list contains five string elements, each representing a sentence or statement.
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

In [23]:
sent    # Displaying the 'sent' list containing five string elements, each representing a sentence or statement


['india won worldcup',
 'rohit played very well',
 'above all is my imagination',
 'bharat mata ki jay',
 'definatly we goona win next worldcup']

In [24]:
# Importing the Tokenizer class from keras.preprocessing.text module for text tokenization
from keras.preprocessing.text import Tokenizer

In [25]:
tokenizer = Tokenizer()  # Creating an instance of the Tokenizer class

In [26]:
tokenizer.fit_on_texts(sent)  # Updates internal vocabulary based on the given text data

In [27]:
tokenizer.word_index  # Returns a dictionary where keys are words and values are their corresponding integer indices

{'worldcup': 1,
 'india': 2,
 'won': 3,
 'rohit': 4,
 'played': 5,
 'very': 6,
 'well': 7,
 'above': 8,
 'all': 9,
 'is': 10,
 'my': 11,
 'imagination': 12,
 'bharat': 13,
 'mata': 14,
 'ki': 15,
 'jay': 16,
 'definatly': 17,
 'we': 18,
 'goona': 19,
 'win': 20,
 'next': 21}

In [28]:
tokenizer.word_counts  # Returns a dictionary where keys are words and values are their counts in the corpus

OrderedDict([('india', 1),
             ('won', 1),
             ('worldcup', 2),
             ('rohit', 1),
             ('played', 1),
             ('very', 1),
             ('well', 1),
             ('above', 1),
             ('all', 1),
             ('is', 1),
             ('my', 1),
             ('imagination', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 1),
             ('jay', 1),
             ('definatly', 1),
             ('we', 1),
             ('goona', 1),
             ('win', 1),
             ('next', 1)])

In [29]:
tokenizer.document_count  # Number of documents (sentences in this case) that were used to fit the Tokenizer

5

In [30]:
tokenizer.texts_to_sequences(sent)  # Converts the input sentences to sequences of integers based on the tokenizer's word index
encoding = tokenizer.texts_to_sequences(sent)

In [31]:
encoding  # The resulting integer sequences obtained after applying text-to-sequence encoding on the input sentences

[[2, 3, 1],
 [4, 5, 6, 7],
 [8, 9, 10, 11, 12],
 [13, 14, 15, 16],
 [17, 18, 19, 20, 21, 1]]

In [32]:
from keras.utils import pad_sequences  # Importing the pad_sequences function from Keras, which is commonly used for sequence padding

In [33]:
pad_sequences(encoding, padding="post")  # Padding sequences with zeros at the end (post padding)

array([[ 2,  3,  1,  0,  0,  0],
       [ 4,  5,  6,  7,  0,  0],
       [ 8,  9, 10, 11, 12,  0],
       [13, 14, 15, 16,  0,  0],
       [17, 18, 19, 20, 21,  1]], dtype=int32)

8. Preparing Text Data for Model:

In [34]:
X_train  # Displaying the training data

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1

In [35]:
y_train  # Displaying the training labels

array([1, 0, 0, ..., 0, 1, 0])

In [36]:
X_train = pad_sequences(X_train, padding="post", maxlen=50)  # Padding the training sequences to a maximum length of 50

In [37]:
X_test = pad_sequences(X_test, padding="post", maxlen=50)  # Padding the test sequences to a maximum length of 50

# 9. Building and Compiling a New Model:

In [38]:
model = Sequential()  # Creating a sequential model in Keras

In [39]:
model.add(SimpleRNN(32,  input_shape = (50, 1)))  # Adding a SimpleRNN layer with 32 units and input shape (50, 1)

In [40]:
model.add(Dense(1,  activation = "sigmoid"))  # Adding a Dense layer with 1 unit and sigmoid activation function

In [41]:
model.summary()  # Displaying the summary of the model architecture

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_1 (SimpleRNN)    (None, 32)                1088      
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 1121 (4.38 KB)
Trainable params: 1121 (4.38 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [42]:
model.compile(
    loss = 'binary_crossentropy',   # Setting the loss function to binary crossentropy
    optimizer = 'adam',             # Using the Adam optimizer
    metrics = ['accuracy']          # Monitoring accuracy as a metric
)

# 10. Model Training:

In [43]:
model.fit(
    X_train,                             # Training data
    y_train,                             # Training labels
    validation_data = (X_test, y_test),  # Validation data for monitoring performance during training
    epochs = 5                           # Number of epochs for training
)

Epoch 1/5
782/782 [==============================] - 21s 22ms/step - loss: 0.6937 - accuracy: 0.5086 - val_loss: 0.7010 - val_accuracy: 0.5014
Epoch 2/5
782/782 [==============================] - 13s 16ms/step - loss: 0.6934 - accuracy: 0.5014 - val_loss: 0.6938 - val_accuracy: 0.5034
Epoch 3/5
782/782 [==============================] - 13s 16ms/step - loss: 0.6930 - accuracy: 0.5037 - val_loss: 0.6939 - val_accuracy: 0.5036
Epoch 4/5
782/782 [==============================] - 14s 18ms/step - loss: 0.6931 - accuracy: 0.5033 - val_loss: 0.6967 - val_accuracy: 0.5022
Epoch 5/5
782/782 [==============================] - 14s 18ms/step - loss: 0.6931 - accuracy: 0.5080 - val_loss: 0.6956 - val_accuracy: 0.5046


###### The model is trained on the preprocessed text data for 5 epochs, using the training and validation sets.
--------------------------------------------------------------------------------

In [44]:
model.predict(X_test)   # Predicting labels for the test data using the trained model


782/782 [==============================] - 4s 5ms/step


array([[0.5360094],
       [0.5360094],
       [0.5360094],
       ...,
       [0.5360094],
       [0.5360094],
       [0.5360094]], dtype=float32)

In [45]:
loss, accuracy = model.evaluate(X_test, y_test)   # Evaluating the model on the test data and getting the loss and accuracy


782/782 [==============================] - 5s 6ms/step - loss: 0.6956 - accuracy: 0.5046


In [46]:
loss   # Displaying the value of the loss


0.6956228017807007